config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :delete]

  resources :beers

  resources :breweries

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_frozen', on: :member
  end

  root 'breweries#index'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'ngbrewerylist', to:'breweries#nglist'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
                       length: { in: 3..15 }

  validates :password, length: { minimum: 4 }

  validates :password, format: { with: /\d.*[A-Z]|[A-Z].*\d/,  message: "has to contain one number and one upper case letter" }

  def self.most_active(n)
    sorted_by_rating_in_desc_order = User.all.select{ |u| u.ratings.any? }.sort_by{ |u| -(u.ratings.count) }
    sorted_by_rating_in_desc_order[0..(n-1)]
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite(category)
    return nil if ratings.empty?

    categroy_ratings = rated(category).inject([]) do |set, item|
      set << {
        item: item,
        rating: rating_of(category, item) }
    end

    categroy_ratings.sort_by { |item| item[:rating] }.last[:item]
  end

  def favorite_brewery
    favorite :brewery
  end

  def favorite_style
    favorite :style
  end

  def rated(category)
    ratings.map{ |r| r.beer.send(category) }.uniq
  end

  def rating_of(category, item)
    ratings_of_item = ratings.select do |r|
      r.beer.send(category) == item
    end
    ratings_of_item.map(&:score).sum / ratings_of_item.count
  end

  def rating_of_style(style)
    rating_of :style, style
  end

  def rating_of_brewery(brewery)
    rating_of :brewery, brewery
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.update_attribute(:admin, false)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_frozen
    user = User.find(params[:id])
    user.update_attribute :frozen_account, (not user.frozen_account)

    new_status = user.frozen_account? ? "frozen" : "non-frozen"

    redirect_to :back, notice:"user activity status changed to #{new_status}"
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if @user == current_user
    respond_to do |format|
      format.html { redirect_to :singout_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
     params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>
  <%= @user.username %>
</h2>

<% if @user.ratings.empty? %>
  <p>has not yet rated any beers</p>
<% else %>
  <p>
    Has made <%= pluralize(@user.ratings.count, 'rating') %>, average <%= @user.average_rating %>
  </p>
<% end %>

<% if @user.beer_clubs.any? %>
  member of
  <% @user.beer_clubs.each do |club| %>
      <%= link_to club.name, club %>
  <% end %>
<% end %>

<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %>
        <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>
<% if current_user && current_user.admin? %>
  <% if @user.frozen_account %>
    <%= link_to "Heat up", toggle_frozen_user_path(@user.id), method: :post, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Freeze", toggle_frozen_user_path(@user.id), method: :post, class: "btn btn-primary" %>
  <% end %>
<% end -%>


<% if @user == current_user %>
  <%= link_to 'Change password', edit_user_path(@user) %>
  <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger"%>
<% end %>